//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryCheckout.WebAppMVC.HelloIndigoService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Book", Namespace="http://schemas.datacontract.org/2004/07/LibraryModel")]
    [System.SerializableAttribute()]
    public partial class Book : LibraryCheckout.WebAppMVC.HelloIndigoService.TableServiceEntityBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ISBNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PublisherField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SynopsisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Author {
            get {
                return this.AuthorField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorField, value) != true)) {
                    this.AuthorField = value;
                    this.RaisePropertyChanged("Author");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ISBN {
            get {
                return this.ISBNField;
            }
            set {
                if ((object.ReferenceEquals(this.ISBNField, value) != true)) {
                    this.ISBNField = value;
                    this.RaisePropertyChanged("ISBN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Publisher {
            get {
                return this.PublisherField;
            }
            set {
                if ((object.ReferenceEquals(this.PublisherField, value) != true)) {
                    this.PublisherField = value;
                    this.RaisePropertyChanged("Publisher");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Synopsis {
            get {
                return this.SynopsisField;
            }
            set {
                if ((object.ReferenceEquals(this.SynopsisField, value) != true)) {
                    this.SynopsisField = value;
                    this.RaisePropertyChanged("Synopsis");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TableServiceEntityBase", Namespace="http://schemas.datacontract.org/2004/07/TableStorageSet")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LibraryCheckout.WebAppMVC.HelloIndigoService.Book))]
    public partial class TableServiceEntityBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PartitionKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RowKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimestampField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartitionKey {
            get {
                return this.PartitionKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.PartitionKeyField, value) != true)) {
                    this.PartitionKeyField = value;
                    this.RaisePropertyChanged("PartitionKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RowKey {
            get {
                return this.RowKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.RowKeyField, value) != true)) {
                    this.RowKeyField = value;
                    this.RaisePropertyChanged("RowKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Timestamp {
            get {
                return this.TimestampField;
            }
            set {
                if ((this.TimestampField.Equals(value) != true)) {
                    this.TimestampField = value;
                    this.RaisePropertyChanged("Timestamp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="uri://blackriverinc.com/helloindigo/LibraryService", ConfigurationName="HelloIndigoService.ILibraryService")]
    public interface ILibraryService {
        
        [System.ServiceModel.OperationContractAttribute(Action="uri://blackriverinc.com/helloindigo/LibraryService/ILibraryService/List", ReplyAction="uri://blackriverinc.com/helloindigo/LibraryService/ILibraryService/ListResponse")]
        LibraryCheckout.WebAppMVC.HelloIndigoService.ListResponse List(LibraryCheckout.WebAppMVC.HelloIndigoService.ListRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="uri://blackriverinc.com/helloindigo/LibraryService/ILibraryService/List", ReplyAction="uri://blackriverinc.com/helloindigo/LibraryService/ILibraryService/ListResponse")]
        System.Threading.Tasks.Task<LibraryCheckout.WebAppMVC.HelloIndigoService.ListResponse> ListAsync(LibraryCheckout.WebAppMVC.HelloIndigoService.ListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="uri://blackriverinc.com/helloindigo/LibraryService/ILibraryService/Read", ReplyAction="uri://blackriverinc.com/helloindigo/LibraryService/ILibraryService/ReadResponse")]
        LibraryCheckout.WebAppMVC.HelloIndigoService.ReadResponse Read(LibraryCheckout.WebAppMVC.HelloIndigoService.ReadRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="uri://blackriverinc.com/helloindigo/LibraryService/ILibraryService/Read", ReplyAction="uri://blackriverinc.com/helloindigo/LibraryService/ILibraryService/ReadResponse")]
        System.Threading.Tasks.Task<LibraryCheckout.WebAppMVC.HelloIndigoService.ReadResponse> ReadAsync(LibraryCheckout.WebAppMVC.HelloIndigoService.ReadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="uri://blackriverinc.com/helloindigo/LibraryService/ILibraryService/Update", ReplyAction="uri://blackriverinc.com/helloindigo/LibraryService/ILibraryService/UpdateResponse" +
            "")]
        LibraryCheckout.WebAppMVC.HelloIndigoService.UpdateResponse Update(LibraryCheckout.WebAppMVC.HelloIndigoService.UpdateRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="uri://blackriverinc.com/helloindigo/LibraryService/ILibraryService/Update", ReplyAction="uri://blackriverinc.com/helloindigo/LibraryService/ILibraryService/UpdateResponse" +
            "")]
        System.Threading.Tasks.Task<LibraryCheckout.WebAppMVC.HelloIndigoService.UpdateResponse> UpdateAsync(LibraryCheckout.WebAppMVC.HelloIndigoService.UpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="uri://blackriverinc.com/helloindigo/LibraryService/ILibraryService/Add", ReplyAction="uri://blackriverinc.com/helloindigo/LibraryService/ILibraryService/AddResponse")]
        bool Add(LibraryCheckout.WebAppMVC.HelloIndigoService.Book book);
        
        [System.ServiceModel.OperationContractAttribute(Action="uri://blackriverinc.com/helloindigo/LibraryService/ILibraryService/Add", ReplyAction="uri://blackriverinc.com/helloindigo/LibraryService/ILibraryService/AddResponse")]
        System.Threading.Tasks.Task<bool> AddAsync(LibraryCheckout.WebAppMVC.HelloIndigoService.Book book);
        
        [System.ServiceModel.OperationContractAttribute(Action="uri://blackriverinc.com/helloindigo/LibraryService/ILibraryService/Delete", ReplyAction="uri://blackriverinc.com/helloindigo/LibraryService/ILibraryService/DeleteResponse" +
            "")]
        bool Delete(string key, System.DateTime timeStamp);
        
        [System.ServiceModel.OperationContractAttribute(Action="uri://blackriverinc.com/helloindigo/LibraryService/ILibraryService/Delete", ReplyAction="uri://blackriverinc.com/helloindigo/LibraryService/ILibraryService/DeleteResponse" +
            "")]
        System.Threading.Tasks.Task<bool> DeleteAsync(string key, System.DateTime timeStamp);
        
        [System.ServiceModel.OperationContractAttribute(Action="uri://blackriverinc.com/helloindigo/LibraryService/ILibraryService/Load", ReplyAction="uri://blackriverinc.com/helloindigo/LibraryService/ILibraryService/LoadResponse")]
        bool Load(System.IO.Stream input);
        
        [System.ServiceModel.OperationContractAttribute(Action="uri://blackriverinc.com/helloindigo/LibraryService/ILibraryService/Load", ReplyAction="uri://blackriverinc.com/helloindigo/LibraryService/ILibraryService/LoadResponse")]
        System.Threading.Tasks.Task<bool> LoadAsync(System.IO.Stream input);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="List", WrapperNamespace="uri://blackriverinc.com/helloindigo/LibraryService", IsWrapped=true)]
    public partial class ListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="uri://blackriverinc.com/helloindigo/LibraryService", Order=0)]
        public string searchKey;
        
        public ListRequest() {
        }
        
        public ListRequest(string searchKey) {
            this.searchKey = searchKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListResponse", WrapperNamespace="uri://blackriverinc.com/helloindigo/LibraryService", IsWrapped=true)]
    public partial class ListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="uri://blackriverinc.com/helloindigo/LibraryService", Order=0)]
        public bool ListResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="uri://blackriverinc.com/helloindigo/LibraryService", Order=1)]
        public LibraryCheckout.WebAppMVC.HelloIndigoService.Book[] books;
        
        public ListResponse() {
        }
        
        public ListResponse(bool ListResult, LibraryCheckout.WebAppMVC.HelloIndigoService.Book[] books) {
            this.ListResult = ListResult;
            this.books = books;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read", WrapperNamespace="uri://blackriverinc.com/helloindigo/LibraryService", IsWrapped=true)]
    public partial class ReadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="uri://blackriverinc.com/helloindigo/LibraryService", Order=0)]
        public string key;
        
        public ReadRequest() {
        }
        
        public ReadRequest(string key) {
            this.key = key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadResponse", WrapperNamespace="uri://blackriverinc.com/helloindigo/LibraryService", IsWrapped=true)]
    public partial class ReadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="uri://blackriverinc.com/helloindigo/LibraryService", Order=0)]
        public bool ReadResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="uri://blackriverinc.com/helloindigo/LibraryService", Order=1)]
        public LibraryCheckout.WebAppMVC.HelloIndigoService.Book book;
        
        public ReadResponse() {
        }
        
        public ReadResponse(bool ReadResult, LibraryCheckout.WebAppMVC.HelloIndigoService.Book book) {
            this.ReadResult = ReadResult;
            this.book = book;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update", WrapperNamespace="uri://blackriverinc.com/helloindigo/LibraryService", IsWrapped=true)]
    public partial class UpdateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="uri://blackriverinc.com/helloindigo/LibraryService", Order=0)]
        public LibraryCheckout.WebAppMVC.HelloIndigoService.Book book;
        
        public UpdateRequest() {
        }
        
        public UpdateRequest(LibraryCheckout.WebAppMVC.HelloIndigoService.Book book) {
            this.book = book;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateResponse", WrapperNamespace="uri://blackriverinc.com/helloindigo/LibraryService", IsWrapped=true)]
    public partial class UpdateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="uri://blackriverinc.com/helloindigo/LibraryService", Order=0)]
        public bool UpdateResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="uri://blackriverinc.com/helloindigo/LibraryService", Order=1)]
        public LibraryCheckout.WebAppMVC.HelloIndigoService.Book book;
        
        public UpdateResponse() {
        }
        
        public UpdateResponse(bool UpdateResult, LibraryCheckout.WebAppMVC.HelloIndigoService.Book book) {
            this.UpdateResult = UpdateResult;
            this.book = book;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILibraryServiceChannel : LibraryCheckout.WebAppMVC.HelloIndigoService.ILibraryService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LibraryServiceClient : System.ServiceModel.ClientBase<LibraryCheckout.WebAppMVC.HelloIndigoService.ILibraryService>, LibraryCheckout.WebAppMVC.HelloIndigoService.ILibraryService {
        
        public LibraryServiceClient() {
        }
        
        public LibraryServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LibraryServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LibraryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LibraryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LibraryCheckout.WebAppMVC.HelloIndigoService.ListResponse LibraryCheckout.WebAppMVC.HelloIndigoService.ILibraryService.List(LibraryCheckout.WebAppMVC.HelloIndigoService.ListRequest request) {
            return base.Channel.List(request);
        }
        
        public bool List(string searchKey, out LibraryCheckout.WebAppMVC.HelloIndigoService.Book[] books) {
            LibraryCheckout.WebAppMVC.HelloIndigoService.ListRequest inValue = new LibraryCheckout.WebAppMVC.HelloIndigoService.ListRequest();
            inValue.searchKey = searchKey;
            LibraryCheckout.WebAppMVC.HelloIndigoService.ListResponse retVal = ((LibraryCheckout.WebAppMVC.HelloIndigoService.ILibraryService)(this)).List(inValue);
            books = retVal.books;
            return retVal.ListResult;
        }
        
        public System.Threading.Tasks.Task<LibraryCheckout.WebAppMVC.HelloIndigoService.ListResponse> ListAsync(LibraryCheckout.WebAppMVC.HelloIndigoService.ListRequest request) {
            return base.Channel.ListAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LibraryCheckout.WebAppMVC.HelloIndigoService.ReadResponse LibraryCheckout.WebAppMVC.HelloIndigoService.ILibraryService.Read(LibraryCheckout.WebAppMVC.HelloIndigoService.ReadRequest request) {
            return base.Channel.Read(request);
        }
        
        public bool Read(string key, out LibraryCheckout.WebAppMVC.HelloIndigoService.Book book) {
            LibraryCheckout.WebAppMVC.HelloIndigoService.ReadRequest inValue = new LibraryCheckout.WebAppMVC.HelloIndigoService.ReadRequest();
            inValue.key = key;
            LibraryCheckout.WebAppMVC.HelloIndigoService.ReadResponse retVal = ((LibraryCheckout.WebAppMVC.HelloIndigoService.ILibraryService)(this)).Read(inValue);
            book = retVal.book;
            return retVal.ReadResult;
        }
        
        public System.Threading.Tasks.Task<LibraryCheckout.WebAppMVC.HelloIndigoService.ReadResponse> ReadAsync(LibraryCheckout.WebAppMVC.HelloIndigoService.ReadRequest request) {
            return base.Channel.ReadAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LibraryCheckout.WebAppMVC.HelloIndigoService.UpdateResponse LibraryCheckout.WebAppMVC.HelloIndigoService.ILibraryService.Update(LibraryCheckout.WebAppMVC.HelloIndigoService.UpdateRequest request) {
            return base.Channel.Update(request);
        }
        
        public bool Update(ref LibraryCheckout.WebAppMVC.HelloIndigoService.Book book) {
            LibraryCheckout.WebAppMVC.HelloIndigoService.UpdateRequest inValue = new LibraryCheckout.WebAppMVC.HelloIndigoService.UpdateRequest();
            inValue.book = book;
            LibraryCheckout.WebAppMVC.HelloIndigoService.UpdateResponse retVal = ((LibraryCheckout.WebAppMVC.HelloIndigoService.ILibraryService)(this)).Update(inValue);
            book = retVal.book;
            return retVal.UpdateResult;
        }
        
        public System.Threading.Tasks.Task<LibraryCheckout.WebAppMVC.HelloIndigoService.UpdateResponse> UpdateAsync(LibraryCheckout.WebAppMVC.HelloIndigoService.UpdateRequest request) {
            return base.Channel.UpdateAsync(request);
        }
        
        public bool Add(LibraryCheckout.WebAppMVC.HelloIndigoService.Book book) {
            return base.Channel.Add(book);
        }
        
        public System.Threading.Tasks.Task<bool> AddAsync(LibraryCheckout.WebAppMVC.HelloIndigoService.Book book) {
            return base.Channel.AddAsync(book);
        }
        
        public bool Delete(string key, System.DateTime timeStamp) {
            return base.Channel.Delete(key, timeStamp);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAsync(string key, System.DateTime timeStamp) {
            return base.Channel.DeleteAsync(key, timeStamp);
        }
        
        public bool Load(System.IO.Stream input) {
            return base.Channel.Load(input);
        }
        
        public System.Threading.Tasks.Task<bool> LoadAsync(System.IO.Stream input) {
            return base.Channel.LoadAsync(input);
        }
    }
}
