//------------------------------------------------------------------------------
// <auto-generated date="02/18/2015 03:29:47">
//     This code was generated from a custom template. The customizations 
//     provide support for Windows Azure Table Storage.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Data.Services.Common;
using System.Web;

using Microsoft.WindowsAzure.StorageClient;

using TableStorageSet;


namespace LibraryModel
{
    /* Entity.Name = 'BookCheckout' */
    public partial class BookCheckout : TableServiceEntityBase
    {
    	// Initialize the 'TableName' to the fully qualifed name of
    	// this Type.
    	static BookCheckout() 
    		{
    		Type type = typeof(BookCheckout);
    		_tableName = type.Name;
    		}
    
    	public new static string TableName
    		{
    		get
    			{
    			return _tableName;
    			}
    		}
    		 
    	// Default Constructor for TableStorageEntity-derived classes
    	// initializes the PartitionKey to the full name of this type.
    	public BookCheckout() 
    		{
    		PartitionKey = TableName;
    		}
    
    	  
        #region RowKey Generator,Parser
    	protected override string buildRowKey()
    		{
    		return string.Join("|", (new Collection<string>()
    							{HttpUtility.UrlEncode(ISBN),
    HttpUtility.UrlEncode(Email)}));
    		}
    
    	protected override void parseRowKey(string rowKey)
    		{
    		string[] keyElements = rowKey.Split('|');
    		ISBN = HttpUtility.UrlDecode(keyElements[0]);
    Email = HttpUtility.UrlDecode(keyElements[1]);
    
    		}

        #endregion

        #region Primitive Properties
    
        public virtual string ISBN
        {
            get; set;
        }
    
        public virtual string Name
        {
            get; set;
        }
    
        public virtual string Address
        {
            get; set;
        }
    
        public virtual string City
        {
            get; set;
        }
    
        public virtual string State
        {
            get; set;
        }
    
        public virtual string ZIP
        {
            get; set;
        }
    
        public virtual string Email
        {
            get; set;
        }

        #endregion

    }
}
