//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library.Model
{
    using System;
    using System.Collections.Generic;
    
    
    [Serializable]
    public partial class Book
    {
        public Book()
        {
            this.BookCheckouts = new HashSet<BookCheckout>();
        }
    
        public Book(Book source) : this()
        {
            if (source != null)
            {
                this.ISBN = source.ISBN;
                this.Title = source.Title;
                this.Publisher = source.Publisher;
                this.Author = source.Author;
                this.Synopsis = source.Synopsis;
            }
        }
    
        public string ISBN { get; set; }
        public string Title { get; set; }
        public string Publisher { get; set; }
        public string Author { get; set; }
        public string Synopsis { get; set; }
    
        public virtual ICollection<BookCheckout> BookCheckouts { get; set; }
    }
}
